let tivi = new TV(1,15);
    let remote = new Remote();
    tivi.turnOn();
    tivi.check();
    console.log('Am Luong:'+tivi.volume);
    console.log('Kenh:'+tivi.getchannel());
    tivi.changeChannel();
    tivi.changeChannel();
    tivi.changeChannel();
    tivi.changeChannel();
    tivi.changeChannel();
    tivi.changeChannel();
    console.log('Kenh:'+tivi.getchannel());
    remote.changeC1(tivi);
    remote.changeC1(tivi);
    remote.changeC1(tivi);
    remote.changeC1(tivi);
    console.log('Kenh:'+tivi.getchannel());
    tivi.changeVolume();
    tivi.changeVolume();
    console.log('Am Luong: '+tivi.volume);
    remote.turnOff(tivi);
    tivi.check();